export const SIDEBAR_ITEMS = [
  {
    text: '集群资源',
    sidebar: 'cluster',
    value: 'admin-workspace',
    icon: 'cib:kubernetes',
    admin: true,
  },
  {
    text: '容器服务',
    sidebar: 'dashboard',
    value: 'resource-dashboard',
    icon: 'cib:kubernetes',
    required: ['tenant'],
  },
  {
    text: '容器服务',
    sidebar: 'projectspace',
    value: 'project-detail',
    icon: 'cib:kubernetes',
    required: ['tenant', 'project'],
  },
  {
    text: '容器服务',
    sidebar: 'workspace',
    value: 'environment-detail',
    icon: 'cib:kubernetes',
    required: ['tenant', 'project', 'environment'],
  },
  {
    text: '服务治理',
    sidebar: 'microservice',
    value: 'microservice',
    icon: 'cib:ripple',
    dependencies: ['istio'],
    admin: 'all',
  },
  {
    text: '服务治理',
    sidebar: 'virtualspace',
    value: 'microservice',
    icon: 'cib:ripple',
    required: ['virtualspace'],
    dependencies: ['istio'],
  },
  {
    text: '可观测性',
    sidebar: 'observe',
    value: 'admin-observe',
    icon: 'ant-design:dashboard-filled',
    admin: true,
  },
  {
    text: '可观测性',
    sidebar: 'workspaceobserve',
    value: 'observe',
    icon: 'ant-design:dashboard-filled',
  },
  {
    text: '平台管理',
    sidebar: 'platform',
    value: 'platform',
    icon: 'mdi:cube-scan',
    admin: true,
  },
];
